
AboutAlgo = []; 

AboutAlgo.name = "Factorial";

AboutAlgo.code = ["def fac(n):",
"   if n <= 1:",
"      return  1",
"   f = fac(n-1)",
"   f = f * n",
"   return f"
];


AboutAlgo[0]  = { n: 0 };
AboutAlgo[0].name = '0!';
AboutAlgo[1]  = { n: 1 };
AboutAlgo[1].name = '1!';
AboutAlgo[3]  = { n: 3 };
AboutAlgo[3].name = '3!';
AboutAlgo[5]  = { n: 5 };
AboutAlgo[5].name = '5!';
AboutAlgo[7]  = { n: 7 };
AboutAlgo[7].name = '7!';


AboutAlgo[0].steps = [
{ action: 'curline', line: 0, text:'fac(n=0)' },
{ action: 'step' },
{ action: 'curline', line: 1,    text:'   if 0 <= 1'},
{ action: 'step' },
{ action: 'curline', line: 2,text: '      return 1'},
{ action: 'step' },
];


AboutAlgo[1].steps = [
{ action: 'curline', line: 0, text:'fac(n=1)' },
{ action: 'step' },
{ action: 'curline', line: 1,    text:'   if 1 <= 1'},
{ action: 'step' },
{ action: 'curline', line: 2,text: '      return 1'},
{ action: 'step' },
];


AboutAlgo[3].steps = [
{ action: 'curline', line: 0, text:'fac(n=3)' },
{ action: 'step' },
{ action: 'curline', line: 1,    text:'   if 3 <= 1'},
{ action: 'step' },
{ action: 'curline', line: 3, text:'   f = fac(3-1)' },
{ action: 'step' },
{ action: 'push', line: 0, text:'fac(n=2)' },
{ action: 'step' },
{ action: 'curline', line: 1,    text:'   if 2 <= 1'},
{ action: 'step' },
{ action: 'curline', line: 3, text:'   f = fac(2-1)' },
{ action: 'step' },
{ action: 'push', line: 0, text:'fac(n=1)' },
{ action: 'step' },
{ action: 'curline', line: 1,    text:'   if 1 <= 1'},
{ action: 'step' },
{ action: 'curline', line: 2,text: '      return 1'},
{ action: 'step' },
{ action: 'pop' },
{ action: 'step' },
{ action: 'line', line: 3,    text:'   f = 1' },
{ action: 'step' },
{ action: 'curline', line: 4, text:'   f = 1 * 2' },
{ action: 'step' },
{ action: 'curline',  line: 5,text:'   return 2'},
{ action: 'step' },
{ action: 'pop' },
{ action: 'line', line: 3,    text:'   f = 2' },
{ action: 'step' },
{ action: 'curline', line: 4, text:'   f = 2 * 3' },
{ action: 'step' },
{ action: 'curline',  line: 5,text:'   return 6'},
];


AboutAlgo[5].steps = [
{ action: 'curline', line: 0, text:'fac(n=5)' },
{ action: 'step' },
{ action: 'curline', line: 1,    text:'   if 5 <= 1'},
{ action: 'step' },
{ action: 'curline', line: 3, text:'   f = fac(5-1)' },
{ action: 'step' },
{ action: 'push', line: 0, text:'fac(n=4)' },
{ action: 'step' },
{ action: 'curline', line: 1,    text:'   if 4 <= 1'},
{ action: 'step' },
{ action: 'curline', line: 3, text:'   f = fac(4-1)' },
{ action: 'step' },
{ action: 'push', line: 0, text:'fac(n=3)' },
{ action: 'step' },
{ action: 'curline', line: 1,    text:'   if 3 <= 1'},
{ action: 'step' },
{ action: 'curline', line: 3, text:'   f = fac(3-1)' },
{ action: 'step' },
{ action: 'push', line: 0, text:'fac(n=2)' },
{ action: 'step' },
{ action: 'curline', line: 1,    text:'   if 2 <= 1'},
{ action: 'step' },
{ action: 'curline', line: 3, text:'   f = fac(2-1)' },
{ action: 'step' },
{ action: 'push', line: 0, text:'fac(n=1)' },
{ action: 'step' },
{ action: 'curline', line: 1,    text:'   if 1 <= 1'},
{ action: 'step' },
{ action: 'curline', line: 2,text: '      return 1'},
{ action: 'step' },
{ action: 'pop' },
{ action: 'step' },
{ action: 'line', line: 3,    text:'   f = 1' },
{ action: 'step' },
{ action: 'curline', line: 4, text:'   f = 1 * 2' },
{ action: 'step' },
{ action: 'curline',  line: 5,text:'   return 2'},
{ action: 'step' },
{ action: 'pop' },
{ action: 'line', line: 3,    text:'   f = 2' },
{ action: 'step' },
{ action: 'curline', line: 4, text:'   f = 2 * 3' },
{ action: 'step' },
{ action: 'curline',  line: 5,text:'   return 6'},
{ action: 'step' },
{ action: 'pop' },
{ action: 'line', line: 3,    text:'   f = 6' },
{ action: 'step' },
{ action: 'curline', line: 4, text:'   f = 6 * 4' },
{ action: 'step' },
{ action: 'curline',  line: 5,text:'   return 24'},
{ action: 'step' },
{ action: 'pop' },
{ action: 'line', line: 3,    text:'   f = 24' },
{ action: 'step' },
{ action: 'curline', line: 4, text:'   f = 24 * 5' },
{ action: 'step' },
{ action: 'curline',  line: 5,text:'   return 120'},
];


AboutAlgo[7].steps = [
{ action: 'curline', line: 0, text:'fac(n=7)' },
{ action: 'step' },
{ action: 'curline', line: 1,    text:'   if 7 <= 1'},
{ action: 'step' },
{ action: 'curline', line: 3, text:'   f = fac(7-1)' },
{ action: 'step' },
{ action: 'push', line: 0, text:'fac(n=6)' },
{ action: 'step' },
{ action: 'curline', line: 1,    text:'   if 6 <= 1'},
{ action: 'step' },
{ action: 'curline', line: 3, text:'   f = fac(6-1)' },
{ action: 'step' },
{ action: 'push', line: 0, text:'fac(n=5)' },
{ action: 'step' },
{ action: 'curline', line: 1,    text:'   if 5 <= 1'},
{ action: 'step' },
{ action: 'curline', line: 3, text:'   f = fac(5-1)' },
{ action: 'step' },
{ action: 'push', line: 0, text:'fac(n=4)' },
{ action: 'step' },
{ action: 'curline', line: 1,    text:'   if 4 <= 1'},
{ action: 'step' },
{ action: 'curline', line: 3, text:'   f = fac(4-1)' },
{ action: 'step' },
{ action: 'push', line: 0, text:'fac(n=3)' },
{ action: 'step' },
{ action: 'curline', line: 1,    text:'   if 3 <= 1'},
{ action: 'step' },
{ action: 'curline', line: 3, text:'   f = fac(3-1)' },
{ action: 'step' },
{ action: 'push', line: 0, text:'fac(n=2)' },
{ action: 'step' },
{ action: 'curline', line: 1,    text:'   if 2 <= 1'},
{ action: 'step' },
{ action: 'curline', line: 3, text:'   f = fac(2-1)' },
{ action: 'step' },
{ action: 'push', line: 0, text:'fac(n=1)' },
{ action: 'step' },
{ action: 'curline', line: 1,    text:'   if 1 <= 1'},
{ action: 'step' },
{ action: 'curline', line: 2,text: '      return 1'},
{ action: 'step' },
{ action: 'pop' },
{ action: 'step' },
{ action: 'line', line: 3,    text:'   f = 1' },
{ action: 'step' },
{ action: 'curline', line: 4, text:'   f = 1 * 2' },
{ action: 'step' },
{ action: 'curline',  line: 5,text:'   return 2'},
{ action: 'step' },
{ action: 'pop' },
{ action: 'line', line: 3,    text:'   f = 2' },
{ action: 'step' },
{ action: 'curline', line: 4, text:'   f = 2 * 3' },
{ action: 'step' },
{ action: 'curline',  line: 5,text:'   return 6'},
{ action: 'step' },
{ action: 'pop' },
{ action: 'line', line: 3,    text:'   f = 6' },
{ action: 'step' },
{ action: 'curline', line: 4, text:'   f = 6 * 4' },
{ action: 'step' },
{ action: 'curline',  line: 5,text:'   return 24'},
{ action: 'step' },
{ action: 'pop' },
{ action: 'line', line: 3,    text:'   f = 24' },
{ action: 'step' },
{ action: 'curline', line: 4, text:'   f = 24 * 5' },
{ action: 'step' },
{ action: 'curline',  line: 5,text:'   return 120'},
{ action: 'step' },
{ action: 'pop' },
{ action: 'line', line: 3,    text:'   f = 120' },
{ action: 'step' },
{ action: 'curline', line: 4, text:'   f = 120 * 6' },
{ action: 'step' },
{ action: 'curline',  line: 5,text:'   return 720'},
{ action: 'step' },
{ action: 'pop' },
{ action: 'line', line: 3,    text:'   f = 720' },
{ action: 'step' },
{ action: 'curline', line: 4, text:'   f = 720 * 7' },
{ action: 'step' },
{ action: 'curline',  line: 5,text:'   return 5040'},
];


